# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25a8e72ea043b619b3199ea218651754ecec0eba8532caffc4a88aee61d4b6c2c1bd8fef16a41f13bd3b1af695a6d8859bf8f4374cf626ddf4101154cbf3c7be

test:
  secret_key_base: 7bc86b0f669c39fc273a49b7dcc6ca5251e3b85ebf88c94974482374c9e6b0c6a286b7239f37bdd75727b96ce761fc837e4fd0301a306bc6ce1a329f29a6a877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
